### ISSUE TITLE
Hi! Can I request additional features?

### ISSUE THREAD

**Issue by BOBODDO** [vgiselbrecht/gise-video-chat#12]
Hi! I look at the code you've developed, practice development hard, and apply it to actual service.

Thank you all the time.

In case, I ask if it is possible to add a function that allows the person who created the room initially to have moderator rights (a function that has the authority to banish others).

Thank you.

**Comment by vgiselbrecht** [comment]
Hi, thanks for the appreciation.

Unfortunately, this is not possible due to the architecture and the lack of authentication.

Regards Valentin
