### ISSUE TITLE
Feature Request!

### ISSUE THREAD

**Issue by BOBODDO** [vgiselbrecht/gise-video-chat#20]
hello developer
We are trying to apply and operate the actual service using the developer's source code.
However, it is unfortunate that there is no way to prevent other users from experiencing inconvenience due to abuse by some users (eg, shouting or singing loudly when entering a room).
When I inquired last time, you said that it is difficult to implement the moderator function. Is it possible to add a function to silence other users?
Thank you.

**Comment by vgiselbrecht** [comment]
Hey BOBODDO,

a function to mute other is easy to implement and already stands up on my to do list.
I will implement it in the next few weeks.

Regards Valentin

**Comment by BOBODDO** [comment]
> Hey BOBODDO,
> 
> a function to mute other is easy to implement and already stands up on my to do list.
> I will implement it in the next few weeks.
> 
> Regards Valentin

Thank you very much!
Have a nice day

**Comment by vgiselbrecht** [comment]
Hey BOBODDO,

in the newest Version 1.0.17  a function to mute other is implemented.
![image](https://user-images.githubusercontent.com/1174991/125095803-da97c480-e0d4-11eb-9ed7-56c4d19daa19.png)

Regards Valentin

**Comment by BOBODDO** [comment]
Sincerely Thanks!
