### ISSUE TITLE
there seems to be a problem when using 'mute' function.

### ISSUE THREAD

**Issue by BOBODDO** [vgiselbrecht/gise-video-chat#23]
Good morning! First of all, thank you so much for implementing the feature.

However, there seems to be a problem when using 'mute' function.

For example, when the current visitor is A, B, C
When A mutes B, B's microphone itself is turned off and C cannot hear B either.

If A mutes B, it would be good if B's sound is not only heard by A and C can still hear B's sound.

**Comment by vgiselbrecht** [comment]
Hey BOBODDO,

i implemented it in the same way as other systems implement it.
I don't quite understand the purpose of muting just one partner. Then it could be that you don't hear half the conversation.

From a technical point of view it would be very easy to implement, because I only have to set the HTML video element to mute. What should the button be called, sound off?

Regards Valentin

**Comment by BOBODDO** [comment]
> Hey BOBODDO,
> 
> i implemented it in the same way as other systems implement it.
> I don't quite understand the purpose of muting just one partner. Then it could be that you don't hear half the conversation.
> 
> From a technical point of view it would be very easy to implement, because I only have to set the HTML video element to mute. What should the button be called, sound off?
> 
> Regards Valentin

Good morning!

The intent you implemented is a good enough intent!

However, when I actually applied the function to the site, there were users playing maliciously.

Malicious users are forcibly muting other people's microphones for no reason. Just for their fun.

So, I want the function to be muted for all people to be given only to the host, and I want the function to be muted only for myself to be given to all users.

Thank you always.

**Comment by BOBODDO** [comment]
> Hey BOBODDO,
> 
> i implemented it in the same way as other systems implement it.
> I don't quite understand the purpose of muting just one partner. Then it could be that you don't hear half the conversation.
> 
> From a technical point of view it would be very easy to implement, because I only have to set the HTML video element to mute. What should the button be called, sound off?
> 
> Regards Valentin

Last time I inquired about the room function
You said that this function is difficult to implement due to structural limitations.

That's why we're asking about how to make the mute function inaudible to only the person who has muted it, rather than completely muting it!

**Comment by vgiselbrecht** [comment]
Yes, now I understand your concerns.
Temporary you can remove the function when you remove following line: https://github.com/vgiselbrecht/gise-video-chat/blob/master/src/assets/ts/Elements/Video.ts#L34

When I get around to it, I will install the sound off function and make both functions to can be deactivated via config.

**Comment by BOBODDO** [comment]
> Yes, now I understand your concerns.
> Temporary you can remove the function when you remove following line: https://github.com/vgiselbrecht/gise-video-chat/blob/master/src/assets/ts/Elements/Video.ts#L34
> 
> When I get around to it, I will install the sound off function and make both functions to can be deactivated via config.

Good morning
I think you may have felt a little rude due to my poor English skills.
I'm really sorry if you felt that way, and thank you as always!

**Comment by vgiselbrecht** [comment]
Hey BOBODDO, 

i habe pushed the changes to the develop brunch: https://github.com/vgiselbrecht/gise-video-chat/tree/develop
In config.json you can deactivate the new features: https://github.com/vgiselbrecht/gise-video-chat/tree/develop#features-1

Can you give me a feedback if it works as you imagined it.

Regards Valentin

**Comment by BOBODDO** [comment]
> Hey BOBODDO,
> 
> i habe pushed the changes to the develop brunch: https://github.com/vgiselbrecht/gise-video-chat/tree/develop
> In config.json you can deactivate the new features: https://github.com/vgiselbrecht/gise-video-chat/tree/develop#features-1
> 
> Can you give me a feedback if it works as you imagined it.
> 
> Regards Valentin

Thank you very much!

The function I was talking about is fully implemented.
The option via editing the json file also works fine.

**Comment by vgiselbrecht** [comment]
Is now released in 1.0.18
