### ISSUE TITLE
I completed any step that give us but its not working 

### ISSUE THREAD

**Issue by Msani02** [vgiselbrecht/gise-video-chat#27]
![problem](https://user-images.githubusercontent.com/106955981/199950180-baef3fd0-77b8-40f2-a285-d1026f30a31d.JPG)
Please if someone get this problem I need help

**Comment by vgiselbrecht** [comment]
Hey Msani02,

the compiled code for the Browser is in the **dist** directory, not in src.
Ideally the the dist directory is the root of your webserver or vhost.

Regards Valentin
