### ISSUE TITLE
Unable to run project locally for development

### ISSUE THREAD

**Issue by erangeles** [vgiselbrecht/gise-video-chat#3]
hello @vgiselbrecht , I want to run the project locally in development, however when i run command `grunt watch`, it does not start any web server where i can access the project. how do I run this project so I can see the application running? i.e `npm start` 

<img width="225" alt="Screen Shot 2021-01-20 at 3 19 19 AM" src="https://user-images.githubusercontent.com/13124163/105153644-4ad26f80-5ace-11eb-931b-06cf01e2b08d.png">

**Comment by vgiselbrecht** [comment]
Hey @erangeles, my npm package does not include a own webserver for development. Ideally you add a local webserver to the dist directory which ist created after "grunt deploy", With "grunt watch" it only compile the code of the changed project files in to the dist directory. I have now written it more clearly in to the README file.

**Comment by erangeles** [comment]
@vgiselbrecht thanks for the response and clarification. I will now close this issue.
