### ISSUE TITLE
Chat is unavailable when using Samsung browser

### ISSUE THREAD

**Issue by BOBODDO** [vgiselbrecht/gise-video-chat#9]
When using the Android Samsung browser, it seems that chat is not available.(https://play.google.com/store/apps/details?id=com.sec.android.app.sbrowser)

please check.

Thank you!

**Comment by vgiselbrecht** [comment]
Hey @BOBODDO,

i test it on the newest version of the Samsung Browser and it works for me.
Can you explain the error in more detail?

Regards Valentin

**Comment by BOBODDO** [comment]
> Hey @BOBODDO,
> 
> i test it on the newest version of the Samsung Browser and it works for me.
> Can you explain the error in more detail?
> 
> Regards Valentin

Hi, It does not work only in Samsung browsers, and works normally in other browsers (chrome, safari).

When you send a chat, nothing happens when you click the send button
Similarly, even if someone sends you a chat, the chat is not visible to users using the Samsung browser.

I was suspicious that it was a problem with my server settings, so I checked if it works properly on the sample site, but the same chat does not work on the https://chat.gise.at sample site.

**Comment by vgiselbrecht** [comment]
Hi @BOBODDO,

i found the error and fixed it in Version 1.0.7 https://github.com/vgiselbrecht/chat/commit/e20ead4a3df22dc5951909f1ef4c23517e079769

Regard Valentin
